{% set version = '0.5.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-broom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/broom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/broom/broom_{{ version }}.tar.gz
  sha256: 4f912b5d9f6b7dfb24793024cdcf47e8c1a70941b907820ad4a53980771868e4

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: AER, akima, AUC, bbmle, betareg, biglm, binGroup, boot, brms, btergm, car, caret, coda, covr, e1071, emmeans, ergm, gam (>= 1.15), gamlss, gamlss.data, gamlss.dist, geepack, ggplot2, glmnet, gmm, Hmisc, irlba, joineRML, Kendall, knitr, ks, Lahman, lavaan, lfe, lme4, lmodel2, lmtest, lsmeans, maps, maptools, MASS, Matrix, mclust, mgcv, muhaz, multcomp, network, nnet, orcutt (>= 2.2), ordinal, plm, plyr, poLCA, psych, quantreg, rgeos, rmarkdown, robust, rsample, rstan, rstanarm, sp, speedglm, statnet.common, survey, survival, testthat, tseries, xergm, zoo
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-backports
    - r-dplyr
    - r-nlme
    - r-purrr
    - r-reshape2
    - r-stringr
    - r-tibble
    - r-tidyr

  run:
    - r-base
    - r-backports
    - r-dplyr
    - r-nlme
    - r-purrr
    - r-reshape2
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('broom')"           # [not win]
    - "\"%R%\" -e \"library('broom')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/tidyverse/broom
  license: MIT + file LICENSE
  summary: Summarizes key information about statistical objects in tidy tibbles. This makes it
    easy to report results, create plots and consistently work with large numbers of
    models at once. Broom provides three verbs that  each provide different types of
    information about a model. tidy() summarizes information about model components
    such as coefficients of a regression. glance() reports information about an entire
    model, such as goodness of fit measures like AIC and BIC. augment() adds information
    about individual observations to a dataset, such as fitted values or influence measures.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Type: Package
# Package: broom
# Title: Convert Statistical Analysis Objects into Tidy Tibbles
# Version: 0.5.0
# Authors@R: c( person("David", "Robinson", email = "admiral.david@gmail.com", role = c("aut", "cre")), person("Alex", "Hayes", email = "alexpghayes@gmail.com", role = "aut"), person("Matthieu", "Gomez", email = "mattg@princeton.edu", role = "ctb"), person("Boris", "Demeshev", email = "boris.demeshev@gmail.com", role = "ctb"), person("Dieter", "Menne", email = "dieter.menne@menne-biomed.de", role = "ctb"), person("Benjamin", "Nutter", email = "nutter@battelle.org", role = "ctb"), person("Luke", "Johnston", email = "luke.johnston@mail.utoronto.ca", role = "ctb"), person("Ben", "Bolker", email = "bolker@mcmaster.ca", role = "ctb"), person("Francois", "Briatte", email = "f.briatte@gmail.com", role = "ctb"), person("Jeffrey", "Arnold", email = "jeffrey.arnold@gmail.com", role = "ctb"), person("Jonah", "Gabry", email = "jsg2201@columbia.edu", role = "ctb"), person("Luciano", "Selzer", email = "luciano.selzer@gmail.com", role = "ctb"), person("Gavin", "Simpson", email = "ucfagls@gmail.com", role = "ctb"), person("Jens", "Preussner", email = " jens.preussner@mpi-bn.mpg.de", role = "ctb"), person("Jay", "Hesselberth", email = "jay.hesselberth@gmail.com", role = "ctb"), person("Hadley", "Wickham", email = "hadley@rstudio.com", role = "ctb"), person("Matthew", "Lincoln", email = "matthew.d.lincoln@gmail.com", role = "ctb"), person("Alessandro", "Gasparini", email = "ag475@leicester.ac.uk", role = "ctb"), person("Lukasz", "Komsta", email = "lukasz.komsta@umlub.pl", role = "ctb"), person("Frederick", "Novometsky", role = "ctb"), person("Wilson", "Freitas", role = "ctb"), person("Michelle", "Evans", role = "ctb"), person("Jason Cory", "Brunson", email = "cornelioid@gmail.com", role = "ctb"), person("Simon", "Jackson", email = "drsimonjackson@gmail.com", role = "ctb"), person("Ben", "Whalley", email = "ben.whalley@plymouth.ac.uk", role = "ctb"), person("Michael", "Kuehn", email = "mkuehn10@gmail.com", role = "ctb"), person("Jorge", "Cimentada", email = "cimentadaj@gmail.com", role = "ctb"), person("Erle", "Holgersen", email = "erle.holgersen@gmail.com", role = "ctb"), person("Karl", "Dunkle Werner", role = "ctb"))
# Maintainer: David Robinson <admiral.david@gmail.com>
# Description: Summarizes key information about statistical objects in tidy tibbles. This makes it easy to report results, create plots and consistently work with large numbers of models at once. Broom provides three verbs that  each provide different types of information about a model. tidy() summarizes information about model components such as coefficients of a regression. glance() reports information about an entire model, such as goodness of fit measures like AIC and BIC. augment() adds information about individual observations to a dataset, such as fitted values or influence measures.
# License: MIT + file LICENSE
# URL: http://github.com/tidyverse/broom
# BugReports: http://github.com/tidyverse/broom/issues
# Depends: R (>= 3.1)
# Imports: backports, dplyr, methods, nlme, purrr, reshape2, stringr, tibble, tidyr
# Suggests: AER, akima, AUC, bbmle, betareg, biglm, binGroup, boot, brms, btergm, car, caret, coda, covr, e1071, emmeans, ergm, gam (>= 1.15), gamlss, gamlss.data, gamlss.dist, geepack, ggplot2, glmnet, gmm, Hmisc, irlba, joineRML, Kendall, knitr, ks, Lahman, lavaan, lfe, lme4, lmodel2, lmtest, lsmeans, maps, maptools, MASS, Matrix, mclust, mgcv, muhaz, multcomp, network, nnet, orcutt (>= 2.2), ordinal, plm, plyr, poLCA, psych, quantreg, rgeos, rmarkdown, robust, rsample, rstan, rstanarm, sp, speedglm, statnet.common, survey, survival, testthat, tseries, xergm, zoo
# VignetteBuilder: knitr
# LazyData: true
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2018-07-16 20:37:11 UTC; alex
# Author: David Robinson [aut, cre], Alex Hayes [aut], Matthieu Gomez [ctb], Boris Demeshev [ctb], Dieter Menne [ctb], Benjamin Nutter [ctb], Luke Johnston [ctb], Ben Bolker [ctb], Francois Briatte [ctb], Jeffrey Arnold [ctb], Jonah Gabry [ctb], Luciano Selzer [ctb], Gavin Simpson [ctb], Jens Preussner [ctb], Jay Hesselberth [ctb], Hadley Wickham [ctb], Matthew Lincoln [ctb], Alessandro Gasparini [ctb], Lukasz Komsta [ctb], Frederick Novometsky [ctb], Wilson Freitas [ctb], Michelle Evans [ctb], Jason Cory Brunson [ctb], Simon Jackson [ctb], Ben Whalley [ctb], Michael Kuehn [ctb], Jorge Cimentada [ctb], Erle Holgersen [ctb], Karl Dunkle Werner [ctb]
# Repository: CRAN
# Date/Publication: 2018-07-17 06:50:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
