travis:
  secure:
    BINSTAR_TOKEN: PG+hPgNYBzWfGByL8ZiFIYaaC+UjXJCrw3AsTiCSuf68bHigeu3X+pZC/LjP1oVT9nm3gJ+URz/+WzxXyMD4lYVr1Ci9gpXKyO2OgYZsJagwtDOalzB4MkTBu2x8ebPMcJp0d/c4hmgRZDCfvizKEe8xiKcjed9KEnB42mRwJyqlxmLwYXQ3T2hGHkzlj8EC/KlRRTTfv1sN+0D1doXfkmmJ8EBkz3KIHcH3KxjrXeQsQM+4jeeJiOEhal9/YjDjyXwHC5R2kQ2JX2Ql3e6KxFi+VPqBnGS64rN7jbpVyOa5wiOYG6PbZheJ6yGmCMUQWlOB3qYw32cw015Z6ix71PUtFUi6+yQ2YGnJSkAFHC+l+hx4lOwBH4NvqJz4lsC34t1IqKBH/+apwneNTanjNoABpf03p9EkGWdnUytZlo/u+8gBVU4ZzYS6YvHtGyg826thkgJ8GTfPFOF+29BkSADrmRv4pc1/pC0bKIx1EY8gYu8/jYsy4SxoxKvdiQJBSjLWpxGzpCTB2KEpWSnpdCkYGGMvcw5CGkEMRbGutisnnnCrvbjL+fv1PP3wNNv/M22pVVYLLnjMoB4MQ3HB3Iyo1Wh1gHPYlhU4pYz9d2rDCZmsqDBJEb9kEogZ1E7HB78B1Ut5evRtimXYoHiWT/KgxCgjFQnpxpk+rxnItZo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
