travis:
  secure:
    BINSTAR_TOKEN: UG9DkUfeVFeHwKV0s+5RZjvErGhcgjT21AIgjXFvowhyn54eYq08nv38loY8Oi649yZ5UGOrD3VovSDGMBUZ7or+BX06C/imlKoFWb/1VvRMShxZKrTtz0m2RICmNsKxZCH1PpZAhsCj+HUnEZMEOxKN/YrMX6obR+QISeGGFahkXHePFSwIfMTpoNnfcOmQKzpEp7pciWr7eeifkTDEIfPsKZjG8WeoVMpv1lgZe7EQDB9orDYYoZYwVkgQwsiU16CG7sBZqZ/lJTe2OXYo7BwbZoGpBafKt/A9sRthc25suzQ0oYgzN0IhUy6Xp9M4wvSaAjsRvK86xSv4/R1s0pl4QuZ+rRgzTFPjtkLTQq9Zm2S0FpBc6SzAP4kEA8GC5DppYHIz/rdNsFft3BtqT13YCUX7KcFsihz2skm6coGa2ai82hBacOPYTO7KfWQZ0HYZmh8CP7BrndRjn/A6sB1rTtxUmfGOn2XrjDK9C9d+dmGIH0YkukktNrOdN77Ln8PK7Q/XkSTyNc0EFCH62fAwjgcFcqa5XiXUE++nlJ1NLBt77qjd7KhLwtobiT5noqrLVxF9omEyGOQ65CRjE620h0xQZdcdYfK8a/tY4Xz+q9aBofto45qQ0gKdlzhM/z/Fa7xNi6uuXh4ZuwPnHr0A2LgFZiHvlaDPPg5iE/I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
