travis:
  secure:
    BINSTAR_TOKEN: SbUoFUCKbcIxG15T2uSwOnG7scPWrGdaBE3M0yyhftatxytohuGspQtZzvf6WhGx4pLttVAwCA/ZtfZk92Aqm1gdBHSIrGXh1tj6ST8sVg6kexqc7vLYBcJ729ALyreT4I7qRD8atwvWwMnhVwIi7MiyzEl1/vONKN12bTOgVTOmq6L34URiGnog0ORtMAmlUltwJ7F1lXnzfjHIVh4HLmOnx85fgWNljlYry5L2h7eUTjVOdtxHc5do7by+DoC0x7iH5zFA/ceLLL+b/U/SDBbXUt3oFj8IIm14c4Gs8C1HiCdT44/Ttrx9MXLstThd2q2o5O+btJQQQYx8dVs7jgsjboo7+Nn5eIpBUW56VR/P5jMygi/ArRM4zXRKRHYmbw6b3pmisR41hR63Uwd3H0FFqu5I/ULs2sGOVlPvTBnSK6DTBvVje72eVI5W+GSTSFtkwFikTkNkZ4Ch+hI9zwZ+2bVLSgD2N4LPvwQ2F02bzHOe/Urb96b6OhNiNz06DNXM1IM72MS3w+7YaQbU56Rg4YCaVI1fb8e62B6lGxGisv0dRHzqVbNSyZqpwWYFTztkFYFOBGIT4kyfitumovexaiXGYrHRL8ipJyG9q4s8FAlkyR/xahoY8z/iMmVXBiOtlrK9la1owUdoCeOoiNSF3RCBv/bOAhb2gaiO+io=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
